### ISSUE TITLE
教程写的很烂

### ISSUE THREAD

**Issue by vvpm** [cwuom/smartdns-wsl-cfg#2]
小白，性子直，就直说。
smartdns配置：申请SSL证书是干什么的？有什么用？去翻了下文档bind-cert-file，bind-cert-key-file不填也会走自签，为何要大费周章再申请 SSL？你也不讲一下为什么？莫名奇妙申请个证书。
这也就不说了
绕过SNI阻断才是重点，你倒好直接踢走，也不说明是在服务端部署还是客户端，也不讲讲smartdns和Accesser联系，默认所有人都知道是吧😅😅😅，既然要在客户端部署，你那smartdns有多大用呢，功劳全在Accesser
照这readme部署，又被你常见问题搞蒙
“将pac文件中的"192.168.1.3:7654"指向你局域网中正在使用此项目的服务器的IP和端口。”
你这是人能写出来的句子吗😅，部署了在其它设备使用，指向其它设备正在使用此项目的服务器的IP和端口，我一字字读也没看懂你什么意思。
“在另一个设备中安装证书，并在代理中启用"使用设置脚本"，并输入目标服务器IP和端口
你这句更魔幻了，怎么安装证书，安装什么证书，在此设备搭建其它设备也要安装一遍那还用这条常见问题吗，每个设备部署一下不就行？还有哪里的“启用'使用设置脚本'”，目标服务器是什么意思。
总结：教程没说请客户端服务端该分别部署哪个，已经A设备搭AccesserB设备咋用
smartdns仅改善dns污染，对sni阻断有jb用，你倒好直接推给别的项目教程也不写
我也是无语了，你这纯README对得起一百多个Star吗

**Comment by cwuom** [comment]
抱歉，现在才看到此issues。很抱歉我的教程并没有讲清楚，因为此教程是个人向的我并没有想到会有这么大的关注度
以下是对你的疑问做出的解答：
> smartdns配置：申请SSL证书是干什么的？有什么用？

如果你有在外地使用的需求的话那申请这个是有必要的，可以开在手机上设置私人DNS并且不会被污染，gfw不能拦截。简单来说如果你想在开流量的情况下访问Google那必须配置证书。具体可以搜索dot(DNS-over-TLS)。当然，如果你只有在局域网使用的需求可以放弃这一步骤并删去配置文件中有关证书的相关配置
> 绕过SNI阻断才是重点，你倒好直接踢走

我认为原作者的[wiki](https://github.com/URenko/Accesser/wiki)中已经做出了很详细的解释和说明，详细到我不需要复述一遍。但是因为我在pac文件上也踩过一次坑，所以还是写下了常见问题。

---

至于你引用的
```
- 将pac文件中的"192.168.1.3:7654"指向你局域网中正在使用此项目的服务器的IP和端口。
- 在另一个设备中安装证书，并在代理中启用"使用设置脚本"，并输入目标服务器IP和端口。
```

我承认是我说的太过草率了，第一个`指向你局域网中正在使用此项目的服务器的IP和端口。`意思是你在哪个设备运行的Accesser就在pac上设置成你那个设备的IPv4地址加上端口号，如果你没有改过端口则就保持默认端口`7654`，因为我是用的笔记本运行的所以需要这一步骤。如果你只是在你本机上运行给本机使用，不需要给局域网的其他设备使用，那么此项直接设置为127.0.0.1即可，即`var proxy = "PROXY 127.0.0.1:7654;";`

---

> 既然要在客户端部署，你那smartdns有多大用呢，功劳全在Accesser

smartdns的主要目的是加快境外网站和国内网站的解析速度，Accesser如果是正常使用的话仅仅是pac代理并不覆盖全部的网站，这会导致有些网站解析速度依旧达不到理想状态。

---

> “在另一个设备中安装证书，并在代理中启用"使用设置脚本"，并输入目标服务器IP和端口

- `怎么安装证书，安装什么证书`在原作者的[wiki](https://github.com/URenko/Accesser/wiki)都给出了说明，如果不安装证书直接访问的话会出现`您的连接不是私密连接(NET::ERR_CERT_INVALID)`之类的错误，至于如何安装这里太长了还是不放出来了，如果还有其他问题你可以自己去wiki看一下。
- 并在代理中启用"使用设置脚本"这句话确实很简短，但是如果你使用的是windows11系统你在设置中打开*网络和Internet*->*代理*应该会看到有关`使用设置脚本`的设置
![image](https://github.com/cwuom/smartdns-wsl-cfg/assets/74239856/27f5cc65-2633-473e-906b-4ea77f7eaa63)
目标服务器则指代你运行Accesser的电脑的ip地址加上端口号和在后面加上一个/pac/。例如`http://localhost:7654/pac/`，这些在原作者文档皆有说明。我在readme中没有必要全部贴上来

---

> 我也是无语了，你这纯README对得起一百多个Star吗

对不起，我的文档确实写的很烂。前面也说了这个是写给自己看的，一开始并没有想到这么高的关注度，因为视频里有人想要教程所以把这个readme贴了出来。至于纯readme的问题，貌似这个仓库除了readme确实没有其他什么可加的了，只是单纯的文档而已。总之谢谢你的反馈，issues就不关了，还有其他问题欢迎再次联系

**Comment by cwuom** [comment]
若无疑问，就先关闭了
